version: 0.2
env:
  shell: bash
  variables:
    APP_NAME: cweventFormat
phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
  build:
    on-failure: ABORT
    commands:
      - 'cd "$CODEBUILD_SRC_DIR/$PROJECT_SUBDIR"'
      - 'make lint-report || :'
      - 'make test-report'
      - 'make build'
  post_build:
    on-failure: ABORT
    commands:
      - 'cd "$CODEBUILD_SRC_DIR/$PROJECT_SUBDIR"'
      - |
        if [[ -n $PACKAGE_BUCKET || $PACKAGE_COUNT -gt 0 ]]; then
          make package
          [[ -z $ENVIRONMENT ]] || make package-${ENVIRONMENT}
        fi
artifacts:
  files:
    - $APP_NAME.zip
  discard-paths: yes
  base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/dist/
reports:
  eslint:
    files:
      - eslint.xml
    base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/reports/
    file-format: JUNITXML
  mocha:
    files:
      - mocha.xml
    base-directory: $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/reports/
    file-format: JUNITXML
cache:
  paths:
    - $CODEBUILD_SRC_DIR/$PROJECT_SUBDIR/node_modules
